### ISSUE TITLE
Opus Support?

### ISSUE THREAD

**Issue by ghost** [DustyDrifter/AltaCast#4]
Feature request:
Can AltaCast be made to include opus support, please? It's a good audio format especially at low bitrates, and it's open source. https://www.opus-codec.org/

The RadioDJ version of AltaCast supposedly supports opus, however what about us users who don't use RadioDJ? I use the standalone version.

**Comment by DustyDrifter** [comment]
The RadioDJ version and standalone version are two separate projects written in two different languages. When I get a break from my studies, I will check into the C++ implementation (i.e. - it's on the list).  :)

**Comment by KevanGP** [comment]
It updates the setting when I run the program as admin.
When I don't run as admin, the bitrate that's displayed on the
server's page changes when I update the box. But the actual audio
quality stays at the level I last left it on when I ran as admin, if
that makes sense.
I can hear the quality in the music when the stream goes through. If
you use AAC Plus and set it to 32 KBPS after running as admin, then
close and reopen it and don't run as admin and set it to 128 KBPS and
listen again, it still will have bad quality because it's actually
still 32 KBPS.

**Comment by KevanGP** [comment]
Sorry I replied to the wrong ticket... You can erase my last comment.

**Comment by encendedor** [comment]
Sorry for opening that old issue. Is altacast standalone opus-ready now? I couldn't find anything about it. Tried to copy opus dll's to the altacast program directory but it isn't choosable in the encoders list.
