### ISSUE TITLE
FLAC support?

### ISSUE THREAD

**Issue by andrew867** [DustyDrifter/AltaCast#6]
I remember that oddsock(-reborn) supported FLAC in an OGG container, how can I enable support in AltaCast?

**Comment by andrew867** [comment]
Well I can see the code is still in this file:
https://github.com/DustyDrifter/AltaCast/blob/master/trunk/AltaCast/src/BasicSettings.cpp#L90

But it doesn't seem to be in the version I have installed with RadioDJ. What do you recommend I try?

**Comment by DustyDrifter** [comment]
The RadioDJ version is a different project than the standalone version. Flac was never coded into it because it was never requested that I'm aware of. I downloaded the files I need and will code it in after my weekly exams.

If you need the capability now, you can use the DSP kit. The RadioDJ DSP plugin has Flac capability. That will temporarily solve the issue until I can code Flac into the RDJ encoder.

**Comment by andrew867** [comment]
Sounds good, thanks for your help! :)
