### ISSUE TITLE
1.1 doesn't work correctly with AAC Plus

### ISSUE THREAD

**Issue by ghost** [DustyDrifter/AltaCast#7]
I'm not trying to use regular AAC, I'm using AAC Plus. I've had this encoder file (that's not listed on the Altacast website) so I'm not sure if you knew AAC Plus still worked in the program.
When using AAC Plus in Altacast 1.1, I'm unable to set the bit rate. The actual bit rate is stuck at a random number, even though the number in the Altacast config box I'm changing to something completely different. Altacast 1.0 didn't have this problem, it just worked. Also AAC Plus doesn't work in mono with Altacast 1.1, while in Altacast 1.0 mono worked up to 64 KBPS.
Here is a link to the encoder file I'm using for AAC Plus, just put this in your Altacast directory and the extra option will be there in the settings.
https://www.sendspace.com/file/6ltisr

**Comment by DustyDrifter** [comment]
Hello,
Thanks for your report.
Yes, I was aware of that particular compatibility. It's an unsupported legacy option for those who choose to explore it. The lack of any reference to it is intentional because of an issue between the original author and the codec owner. To avoid the same issue, I simply make no mention of it so the end user can discover it on their own. 
 The code for the codec you reference was not touched between 1.0 and 1.1. I tested the file you provided and cannot reproduce the issue you describe.  It sounds like the config file isn't saving, Without knowing your operating environment, all I can suggest is to ensure the program has administrator privileges.
Thanks.

**Comment by ghost** [comment]
It updates the setting when I run the program as admin.
When I don't run as admin, the bitrate that's displayed on the
server's page changes when I update the box. But the actual audio
quality stays at the level I last left it on when I ran as admin, if
that makes sense.
I can hear the quality in the music when the stream goes through. If
you use AAC Plus and set it to 32 KBPS after running as admin, then
close and reopen it and don't run as admin and set it to 128 KBPS and
listen again, it still will have bad quality because it's actually
still 32 KBPS.

**Comment by DustyDrifter** [comment]
> It updates the setting when I run the program as admin.
> When I don't run as admin, the bitrate that's displayed on the
> server's page changes when I update the box. But the actual audio
> quality stays at the level I last left it on when I ran as admin, if
> that makes sense.

It does. You have a permissions issue. This is not a programming problem. A quick fix would be to right click on the desktop icon, select properties, then compatibility, and check the "Run as Administrator" box (Windows 7).

Thank you for using AltaCast. Issue closed

DD
